---
- hosts: all
  become: yes
  tasks:
  - name: update and install apache2
    apt:
     name: apache3
     state: present
     update_cache: yes
  - name: install mysql server
    apt:
      name: mysql-server
      state: present
  - name: install php server
    apt:
      name: {{ item }}
      state: present
    with_item:
      - php 
      - libapache2-mod-php 
      - php-mcrypt 
      - php-mysql
  - name: restart apache
    service:
      name: apache2
      state: restarted